spring:
  cloud:
    gateway:
      routes:
        # 商品服务
        - id: product_route
          # 匹配后提供服务的地址
          uri: lb://gulimall-product
          # 匹配规则
          predicates:
            - Path=/api/product/**
          # 过滤器配置
          filters:
            # 路径重写 /api/** ==> /**
            - RewritePath=/api/(?<segment>.*), /$\{segment}

        # 认证服务
        - id: auth_route
          # 匹配后提供服务的地址
          uri: lb://gulimall-auth
          # 匹配规则
          predicates:
            - Path=/api/auth/**
          # 过滤器配置
          filters:
            # 路径重写 /api/** ==> /**
            - RewritePath=/api/(?<segment>.*), /$\{segment}

        # 会员服务
        - id: member_route
          # 匹配后提供服务的地址
          uri: lb://gulimall-member
          # 匹配规则
          predicates:
            - Path=/api/member/**
          # 过滤器配置
          filters:
            # 路径重写 /api/** ==> /**
            - RewritePath=/api/(?<segment>.*), /$\{segment}

        # 仓储服务
        - id: storage_route
          # 匹配后提供服务的地址
          uri: lb://gulimall-storage
          # 匹配规则
          predicates:
            - Path=/api/storage/**
          # 过滤器配置
          filters:
            # 路径重写 /api/** ==> /**
            - RewritePath=/api/(?<segment>.*), /$\{segment}

        # 搜索服务
        - id: search_route
          # 匹配后提供服务的地址
          uri: lb://gulimall-search
          # 匹配规则
          predicates:
            - Path=/api/search/**
          # 过滤器配置
          filters:
            # 路径重写 /api/** ==> /**
            - RewritePath=/api/(?<segment>.*), /$\{segment}

        # 第三方服务-oss服务
        - id: third_oss_route
          # 匹配后提供服务的地址
          uri: lb://gulimall-module-oss
          # 匹配规则
          predicates:
            - Path=/api/third/oss/**
          # 过滤器配置
          filters:
            # 路径重写 /api/** ==> /**
            - RewritePath=/api/third/(?<segment>.*), /$\{segment}

        # 后台管理服务
        - id: admin_route
          # 匹配后提供服务的地址
          uri: lb://gulimall-admin
          # 匹配规则
          predicates:
            - Path=/api/**
          # 过滤器配置
          filters:
            - RewritePath=/api/(?<segment>.*), /admin/$\{segment}

        # 首页、商品详情页
        - id: gulimall_host_route
          # 匹配后提供服务的地址
          uri: lb://gulimall-product
          # 匹配规则
          predicates:
            - Host=gulimall.com,item.gulimall.com
          # 过滤器配置
          filters:
            # 路径重写 /** ==> /product/**
            - RewritePath=/(?<segment>.*), /product/$\{segment}

        # 搜索页
        - id: search_host_route
          # 匹配后提供服务的地址
          uri: lb://gulimall-search
          # 匹配规则
          predicates:
            - Host=search.gulimall.com
          # 过滤器配置
          filters:
            # 路径重写 /** ==> /search/**
            - RewritePath=/(?<segment>.*), /search/$\{segment}

        # 登录、注册
        - id: auth_host_route
          # 匹配后提供服务的地址
          uri: lb://gulimall-auth
          # 匹配规则
          predicates:
            - Host=auth.gulimall.com
          # 过滤器配置
          filters:
            # 路径重写 /** ==> /search/**
            - RewritePath=/(?<segment>.*), /auth/$\{segment}

      discovery:
        locator:
          # 设置为true表明spring cloud gateway开启服务发现和路由的功能，
          # 网关自动根据注册中心的服务名为每个服务创建一个router，将以服务名开头的请求路径转发到对应的服务
          enabled: true
          # 启动 locator.enabled=true 自动路由时，路由的路径默认会使用大写ID，若想要使用小写ID，可将lowerCaseServiceId设置为true
          lower-case-service-id: true
          filters:
            # 重写过滤链，解决项目设置了 server.servlet.context-path 导致 locator.enabled=true 默认路由策略404的问题
            - PreserveHostHeader
