spring:
  cloud:
    gateway:
      routes:
        # 商品服务
        - id: product_route
          # 匹配后提供服务的地址
          uri: lb://gulimall-product
          # 匹配规则
          predicates:
            - Path=/api/product/**
          # 过滤器配置
          filters:
            # 路径重写 /api/** ==> /**
            - RewritePath=/api/(?<segment>.*), /$\{segment}

        # 第三方服务-oss服务
        - id: third_oss_route
          # 匹配后提供服务的地址
          uri: lb://gulimall-module-oss
          # 匹配规则
          predicates:
            - Path=/api/third/oss/**
          # 过滤器配置
          filters:
            # 路径重写 /api/** ==> /**
            - RewritePath=/api/third/(?<segment>.*), /$\{segment}

        # 后台管理服务
        - id: admin_route
          # 匹配后提供服务的地址
          uri: lb://gulimall-admin
          # 匹配规则
          predicates:
            - Path=/api/**
          # 过滤器配置
          filters:
            - RewritePath=/api/(?<segment>.*), /admin/$\{segment}
